"""Storage contracts used by production repository adapters.

The application currently ships with SQLite for local, reviewable deployments. This
contract isolates the v2 append-only evidence and result methods needed by a PostgreSQL
adapter without allowing API handlers to rely on SQLite details.
"""
from __future__ import annotations

from typing import Protocol

from .bridge_events import BridgeEventV2
from .cross_chain_v2 import BridgeRouteV2, CrossChainLinkV2
from .domain import InvestigationCaseV2, InvestigationResultV2, RawEvidenceArtifact


class InvestigationRepositoryV2(Protocol):
    def get_investigation_case_v2(self, case_id: str) -> InvestigationCaseV2 | None: ...
    def save_raw_evidence_artifact_v2(self, artifact: RawEvidenceArtifact) -> RawEvidenceArtifact: ...
    def get_raw_evidence_artifact_v2(self, artifact_id: str) -> RawEvidenceArtifact | None: ...
    def save_bridge_route_v2(self, route: BridgeRouteV2) -> BridgeRouteV2: ...
    def get_bridge_route_v2(self, route_id: str) -> BridgeRouteV2 | None: ...
    def save_bridge_event_v2(self, event: BridgeEventV2) -> BridgeEventV2: ...
    def get_bridge_event_v2(self, event_id: str) -> BridgeEventV2 | None: ...
    def save_cross_chain_link_v2(self, link: CrossChainLinkV2) -> CrossChainLinkV2: ...
    def save_investigation_result_v2(self, result: InvestigationResultV2) -> InvestigationResultV2: ...
